server:
  port: 80
spring:
  thymeleaf:
    check-template-location: false
  profiles:
    active: desenvolvimento
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus